import { catchError } from 'rxjs/operators';
…
//emit error
const source = throwError('This is an error!');
const example = source.pipe(catchError(val => of(`I caught: ${val}`)));
//output: 'I caught: This is an error'
//
